### ISSUE TITLE
Major issue

### ISSUE THREAD

**Issue by SavvyWizardMan** [leecharlenej/theodinproject#1]
I assume the other issues are a work in progress, so my main focus is only on this critical one. The following code:

`document.getElementById("allBooks").innerHTML = allBooksHTML;`

Allows for cross site scritping attacks. This means that if I were to use the onerror event attribute with the img tag as so:

`<img src onerror="alert('youve been hacked')">`

then: 

![Screenshot 2024-08-24 120722](https://github.com/user-attachments/assets/fce9a440-edc9-4eee-b60e-9e6644877b79)

When you allow users to write to your form inputs and use innerHTML to display what users type, the content written can be treated as HTML if proper syntax is typed. If someone were to write more malicious code into the prompt, they could get their hands on sensitive data.

I'd recommend finding a different technique for adding the HTML for the "book cards" without the use of innerHTML. A common approach I've seen from other projects is by creating the div that is the card and all it's children individually with `document.createElement()`, adding the classes to each element as needed with `element.classList.add()` (element.setAttribute() for the 'data- attribute'), and then append each child element to the parent element with parentElement.appendChild(). The most important one though is using .innerText to write the text that users put into the inputs onto an element.

**Comment by leecharlenej** [comment]
Hi, thank you for your message! I have added DOMPurify to sanitize the inputs.

I am still relatively new to JavaScript and one of my challenges for this project is that I am adding quite a huge amount of HTML using JS and hence, opted to use innerHTML. Are there any other alternatives besides adding the elements individually, as suggested?

**Comment by SavvyWizardMan** [comment]
Uhh sorry I'm kinda new as well to give a proper answer. I'm sure there is but based on a few of the projects that I've seen submitted on TOP they all created each element individually.

Yeah, if you were to take the approach I'm mentioning, then something like this would be used instead:
   ```
    const title = formDialog.querySelector("input[name='title']").value;
    const author = formDialog.querySelector("input[name='author']").value;
    const pages = formDialog.querySelector("input[name='pages']").value;
    const status = formDialog.querySelector("input[value='read']:checked");

    const newBook = new Book (index, title, author, pages, status);
    myLibrary.push(newBook);

    const allBooks = document.querySelector('#allBooks');

 const book = document.createElement('div');
 const hr = document.createElement('hr');
 const hr2 = document.createElement('hr');
 const bookHeader = document.createElement('div');
 const titleDiv = document.createElement('div');
 const authorDiv = document.createElement('div');
 const pagesDiv = document.createElement('div');
 const statusDiv = document.createElement('div');
 const bookFooter = document.createElement('div');
 const deleteIcons = document.createElement('div');
 const deleteButton = document.createElement('button');
 const deleteSvg = document.createElement('img');
 const spanDelete = document.createElement('span');
 const readIcons = document.createElement('div');
 const readButton = document.createElement('button');
 const readSvg = document.createElement('img');
 const spanRead = document.createElement('span');

 book.classList.add('book');
 bookHeader.classList.add('book-header');
 titleDiv.classList.add('title');
 titleDiv.innerText = title;
 authorDiv.classList.add('author');
 authorDiv.innerText = author;
 pagesDiv.classList.add('pages');
 pagesDiv.innerText = pages;
 statusDiv.classList.add('status');
 statusDiv.innerText = `[${newBook.status ? 'read' : 'not read'}]`;
 statusDiv.setAttribute('data-index', `${newBook.index}`);
 bookFooter.classList.add('book-footer');
 deleteIcons.classList.add('icons');
 deleteButton.classList.add('deleteButton');
 deleteSvg.setAttribute('src', "assets/img/book-remove.svg");
 deleteButton.setAttribute('data-index', `${newBook.index}`);
 spanDelete.classList.add('icon-caption');
 spanDelete.innerText = "Delete";
 readIcons.classList.add('icons');
 readButton.classList.add('readButton');
 readButton.setAttribute('data-index', `${newBook.index}`);
 spanRead.classList.add('icon-caption');
 spanRead.innerText = "Read";
 readSvg.setAttribute('src', "assets/img/book-edit.svg");
 
 book.appendChild(hr);
 book.appendChild(bookHeader);
 book.appendChild(hr2);
 book.appendChild(bookFooter);
 bookHeader.appendChild(titleDiv);
 bookHeader.appendChild(authorDiv);
 bookHeader.appendChild(pagesDiv);
 bookHeader.appendChild(statusDiv);
 bookFooter.appendChild(deleteIcons);
 bookFooter.appendChild(readIcons);
 deleteIcons.appendChild(deleteButton);
 deleteButton.appendChild(deleteSvg);
 deleteButton.appendChild(spanDelete);
 readIcons.appendChild(readButton);
 readButton.appendChild(readSvg);
 readButton.appendChild(spanRead);

 allBooks.appendChild(book);

```

... yeah thats kinda lengthy (assuming I didn't make it unnecessarily long). Your solution seems to work pretty well, so nice job!

**Comment by leecharlenej** [comment]
Thanks so much for typing that out for me! I guess using one of the JS libraries might help. I'll update when i find one.

Anyway, thanks sm for this discussion (: Helps with my Odin journey!

**Comment by SavvyWizardMan** [comment]
No problem! Always glad to help when I can. Good luck on your journey!
